source:
  location: sample_720p.h264

streammux:
  batch-size: 1
  batched-push-timeout: 40000
  width: 1920
  height: 1080

# Inference using nvinfer:
primary-gie:
  plugin-type: 0
  config-file-path: config_infer_primary_yoloV8.txt