source:
  location: ../data/sample_720p.h264

streammux:
  batch-size: 1
  batched-push-timeout: 40000
  width: 640
  height: 384

# Inference using nvinfer:
primary-gie:
  plugin-type: 0
  config-file-path: ./config_infer_primary_yoloV8.txt

tracker:
  enable: 1
  tracker-width: 640
  tracker-height: 384
#  gpu-id=0
  ll-lib-file: ./../libByteTracker.so
#  enable-batch-process=1